<LivePlotWidget>:
    canvas.before:
        Color:
            rgba: 0, 0, 0, 1    # 黑色背景
        Rectangle:
            pos: self.pos
            size: self.size

    canvas.after:
        Color:
            rgba: 0.49, 0.88, 1, 1   # 青色：外径
        Line:
            points: self.outer_points
            width: 1.5

        Color:
            rgba: 0.8, 0.4, 1, 1     # 紫色：内径
        Line:
            points: self.inner_points
            width: 1.2
