<AlarmScreen>:
    name: "alarm"
    MDBoxLayout:
        orientation: "vertical"

        MDTopAppBar:
            type: "small"

            MDTopAppBarLeadingButtonContainer:
                MDActionTopAppBarButton:
                    icon: "arrow-left"
                    on_release: app.change_screen("home")

            MDTopAppBarTitle:
                text: "FRP Pipe - Alarms"
                halign: "center"

        MDBoxLayout:
            padding: "24dp"

            MDCard:
                orientation: "vertical"
                padding: "24dp"
                radius: [16, 16, 16, 16]
                md_bg_color: 0.17, 0.19, 0.21, 1

                MDLabel:
                    text: "Alarm List (TODO)"
                    theme_text_color: "Secondary"
