<AlarmScreen>:
    name: "alarm"
    MDBoxLayout:
        orientation: "vertical"

        MDTopAppBar:
            type: "small"

            MDTopAppBarLeadingButtonContainer:
                MDActionTopAppBarButton:
                    icon: "arrow-left"
                    on_release: app.change_screen("home")

            MDTopAppBarTitle:
                text: app.i18n.current_lang and app._("alarm_title")
                halign: "center"

            MDTopAppBarTrailingButtonContainer:
                MDActionTopAppBarButton:
                    icon: "translate"
                    on_release: app.toggle_language()

        MDBoxLayout:
            padding: "24dp"

            MDCard:
                orientation: "vertical"
                padding: "24dp"
                radius: [16, 16, 16, 16]
                md_bg_color: 0.17, 0.19, 0.21, 1

                MDLabel:
                    text: app.i18n.current_lang and app._("alarm_list_title")
                    theme_text_color: "Secondary"

