<AutoMeasureScreen>:
    name: "auto"

    MDBoxLayout:
        orientation: "vertical"

        # 顶部工具栏
        MDTopAppBar:
            type: "small"

            MDTopAppBarLeadingButtonContainer:
                MDActionTopAppBarButton:
                    icon: "arrow-left"
                    on_release: app.change_screen("home")

            MDTopAppBarTitle:
                text: app.i18n.current_lang and app._("auto_title")
                halign: "center"

            MDTopAppBarTrailingButtonContainer:
                MDActionTopAppBarButton:
                    icon: "play-circle"
                    on_release: root.start_auto()
                MDActionTopAppBarButton:
                    icon: "translate"
                    on_release: app.toggle_language()
