#:kivy 2.3.0
# Global fonts
<Label>:
    font_name: "MSYH"

 

<MDIconButton>:
    font_name: "MSYH"

<MDRectangleFlatButton>:
    font_name: "MSYH"

#:include kv/widgets/live_plot.kv
#:include kv/home.kv
#:include kv/resultcard.kv
#:include kv/infoitem.kv
#:include kv/statusinfocard.kv
#:include kv/peripheralstatus.kv
#:include kv/homeactioncard.kv
#:include kv/auto.kv
#:include kv/manual.kv
#:include kv/settings.kv
#:include kv/result.kv
#:include kv/alarm.kv

ScreenManager:
    HomeScreen:
    AutoMeasureScreen:
    ManualScreen:
    SettingsScreen:
    ResultScreen:
    AlarmScreen:
