<PeripheralStatusRow@MDBoxLayout>:
    text: ""
    icon_color: 0, 1, 0, 1  # default green
    orientation: "horizontal"
    spacing: "10dp"
    padding: [0, 2, 0, 2]
    size_hint_y: None
    height: self.minimum_height
    MDLabel:
        text: root.text
        size_hint_x: 1
        halign: "left"
    MDIcon:
        icon: "checkbox-blank-circle"
        size_hint_x: None
        size: "16dp", "16dp"
        theme_text_color: "Custom"
        text_color: root.icon_color

