<ResultCard@MDCard>:
    title: ""
    value: ""
    unit: ""
    status_icon: "checkbox-blank-circle-outline"
    padding: "12dp"
    radius: [10, 10, 10, 10]
    MDBoxLayout:
        orientation: "vertical"
        spacing: "6dp"
        MDLabel:
            text: root.title
            theme_text_color: "Secondary"
        MDLabel:
            text: root.value
        MDLabel:
            text: root.unit
            theme_text_color: "Secondary"
