<SettingsScreen>:
    name: "settings"
    MDBoxLayout:
        orientation: "vertical"
        padding: dp(16)
        spacing: dp(16)

        MDTopAppBar:
            type: "small"

            MDTopAppBarLeadingButtonContainer:
                MDActionTopAppBarButton:
                    icon: "arrow-left"
                    on_release: app.change_screen("home")

            MDTopAppBarTitle:
                text: app.i18n.current_lang and app._("settings_title")
                halign: "center"

            MDTopAppBarTrailingButtonContainer:
                MDActionTopAppBarButton:
                    icon: "translate"
                    on_release: app.toggle_language()

        MDBoxLayout:
            orientation: "vertical"
            spacing: dp(12)

            MDTextField:
                id: plc_ip_field
                hint_text: app.i18n.current_lang and app._("settings_plc_ip_hint")
                text: "192.168.0.10"

            MDTextField:
                id: plc_port_field
                hint_text: app.i18n.current_lang and app._("settings_plc_port_hint")
                text: "502"
                input_filter: "int"

            MDTextField:
                id: samples_field
                hint_text: app.i18n.current_lang and app._("settings_samples_hint")
                text: "180"
                input_filter: "int"

        MDBoxLayout:
            size_hint_y: None
            height: dp(48)
            spacing: dp(12)
            padding: 0, dp(8), 0, 0

            Widget:
            MDRaisedButton:
                text: app.i18n.current_lang and app._("settings_apply")
                on_release: root.on_apply_button()

